(() => {
'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const screens={home:$('#homeScreen'),age:$('#ageScreen'),game:$('#gameScreen'),finish:$('#finishScreen')};
const hud=$('#hud'),starCount=$('#starCount'),roundText=$('#roundText'),choicesEl=$('#choices'),questionText=$('#questionText'),questionKicker=$('#questionKicker'),replayButton=$('#replayButton'),soundButton=$('#soundButton'),soundIcon=$('#soundIcon'),feedback=$('#feedback'),feedbackTitle=$('#feedbackTitle'),feedbackSubtitle=$('#feedbackSubtitle'),feedbackIcon=$('#feedbackIcon'),confetti=$('#confetti'),finalStars=$('#finalStars');
const COLORS=[['red','الحمراء','#ff8176'],['blue','الزرقاء','#70cfe9'],['yellow','الصفراء','#ffd867'],['green','الخضراء','#79c96c'],['purple','البنفسجية','#ad92e8'],['pink','الوردية','#ff9fc4']].map(([id,name,hex])=>({id,name,hex}));
const ANIMALS=[['lion','الأسد','🦁'],['elephant','الفيل','🐘'],['monkey','القرد','🐵'],['giraffe','الزرافة','🦒'],['panda','الباندا','🐼'],['frog','الضفدع','🐸'],['tiger','النمر','🐯'],['zebra','الحمار الوحشي','🦓'],['hippo','فرس النهر','🦛'],['rabbit','الأرنب','🐰'],['bear','الدب','🐻'],['fox','الثعلب','🦊']].map(([id,name,emoji])=>({id,name,emoji}));
const SHAPES=[['circle','الدائرة','●'],['square','المربع','■'],['triangle','المثلث','▲'],['star','النجمة','★'],['heart','القلب','♥']].map(([id,name,symbol])=>({id,name,symbol}));
const state={age:'2-3',round:0,totalRounds:12,stars:0,streak:0,muted:localStorage.getItem('bubbleSafariMuted')==='1',currentQuestion:null,locked:false,lastAnimal:null,lastType:null,audioContext:null};
function showScreen(name){Object.entries(screens).forEach(([k,e])=>{e.classList.toggle('screen-active',k===name);e.setAttribute('aria-hidden',k===name?'false':'true')});hud.classList.toggle('hidden',name!=='game');requestAnimationFrame(()=>focusFirst(name))}
function focusFirst(name){const t=$('[data-focusable]:not([disabled])',screens[name]);if(t)setTvFocus(t)}
function setTvFocus(el){$$('.tv-focus').forEach(n=>n.classList.remove('tv-focus'));if(!el)return;el.classList.add('tv-focus');try{el.focus({preventScroll:true})}catch{el.focus()}}
function activeFocusables(){const s=$('.screen-active');return s?$$('[data-focusable]:not([disabled])',s).filter(e=>{const x=getComputedStyle(e);return x.display!=='none'&&x.visibility!=='hidden'&&e.offsetParent!==null}):[]}
function spatialNavigate(dir){const items=activeFocusables();if(!items.length)return;const cur=items.includes(document.activeElement)?document.activeElement:$('.tv-focus');if(!cur||!items.includes(cur)){setTvFocus(items[0]);return}const a=cur.getBoundingClientRect(),fx=a.left+a.width/2,fy=a.top+a.height/2;let best=null,score=Infinity;items.forEach(item=>{if(item===cur)return;const r=item.getBoundingClientRect(),dx=r.left+r.width/2-fx,dy=r.top+r.height/2-fy,ok=(dir==='left'&&dx<-8)||(dir==='right'&&dx>8)||(dir==='up'&&dy<-8)||(dir==='down'&&dy>8);if(!ok)return;const p=(dir==='left'||dir==='right')?Math.abs(dx):Math.abs(dy),s=(dir==='left'||dir==='right')?Math.abs(dy):Math.abs(dx),v=p+s*2.15;if(v<score){score=v;best=item}});if(best)setTvFocus(best)}
document.addEventListener('keydown',e=>{const k=e.key;if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Enter',' ','Escape','Backspace'].includes(k))e.preventDefault();if(k.startsWith('Arrow'))spatialNavigate(k.slice(5).toLowerCase());if(k==='Enter'||k===' '){const el=document.activeElement;if(el&&el.matches('[data-focusable]'))el.click()}if(k==='Escape'||k==='Backspace')handleBack()},{passive:false});
function handleBack(){if(screens.game.classList.contains('screen-active')){state.locked=false;cancelSpeech();showScreen('age')}else if(screens.age.classList.contains('screen-active')||screens.finish.classList.contains('screen-active'))showScreen('home')}
const randomFrom=a=>a[Math.floor(Math.random()*a.length)];function shuffle(a){const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c}
function pickUnique(pool,count,target){return shuffle([target,...shuffle(pool.filter(x=>x.id!==target.id)).slice(0,count-1)])}
function availableTypes(){if(state.age==='2-3')return state.round<4?['animal','animal','color']:['animal','color','animal','color','shape'];return state.round<4?['animal','color','number']:['animal','color','number','shape','number']}
function makeQuestion(){let types=availableTypes(),type=randomFrom(types);if(type===state.lastType&&Math.random()<.72)type=randomFrom(types.filter(t=>t!==state.lastType));state.lastType=type;
if(type==='animal'){let target=randomFrom(ANIMALS);if(target.id===state.lastAnimal)target=randomFrom(ANIMALS.filter(a=>a.id!==state.lastAnimal));state.lastAnimal=target.id;return{type,kicker:'ابحث عن الحيوان',prompt:`أين ${target.name}؟`,speech:`أين ${target.name}؟`,options:pickUnique(ANIMALS,3,target).map((a,i)=>({id:a.id,label:a.name,symbol:a.emoji,color:COLORS[(state.round+i)%COLORS.length].hex,correct:a.id===target.id,kind:'animal'}))}}
if(type==='color'){const cs=shuffle(COLORS).slice(0,3),target=randomFrom(cs),animal=randomFrom(ANIMALS);return{type,kicker:'ابحث عن اللون',prompt:`أين الفقاعة ${target.name}؟`,speech:`أين الفقاعة ${target.name}؟`,options:shuffle(cs.map(c=>({id:c.id,label:c.name.replace('ال',''),symbol:animal.emoji,color:c.hex,correct:c.id===target.id,kind:'color'})))}}
if(type==='shape'){const ss=shuffle(SHAPES).slice(0,3),target=randomFrom(ss);return{type,kicker:'ابحث عن الشكل',prompt:`أين ${target.name}؟`,speech:`أين ${target.name}؟`,options:shuffle(ss.map((s,i)=>({id:s.id,label:s.name,symbol:s.symbol,color:COLORS[(state.round+i+1)%COLORS.length].hex,correct:s.id===target.id,kind:'shape'})))}}
const nums=shuffle([1,2,3,4,5]).slice(0,3),target=randomFrom(nums);return{type:'number',kicker:'ابحث عن الرقم',prompt:`أين الرقم ${target}؟`,speech:`أين الرقم ${target}؟`,options:shuffle(nums.map((n,i)=>({id:String(n),label:`الرقم ${n}`,symbol:String(n),color:COLORS[(state.round+i+2)%COLORS.length].hex,correct:n===target,kind:'number'})))}}
function shade(hex,p){const n=parseInt(hex.slice(1),16),a=Math.round(2.55*p),r=Math.max(0,Math.min(255,(n>>16)+a)),g=Math.max(0,Math.min(255,((n>>8)&255)+a)),b=Math.max(0,Math.min(255,(n&255)+a));return`#${(0x1000000+r*0x10000+g*0x100+b).toString(16).slice(1)}`}
function renderQuestion(){state.currentQuestion=makeQuestion();questionKicker.textContent=state.currentQuestion.kicker;questionText.textContent=state.currentQuestion.prompt;roundText.textContent=`${state.round+1} / ${state.totalRounds}`;starCount.textContent=state.stars;choicesEl.innerHTML='';state.currentQuestion.options.forEach((o,i)=>{const b=document.createElement('button');b.type='button';b.className='choice focusable';b.dataset.focusable='';b.setAttribute('aria-label',o.label);b.innerHTML=`<span class="choice-bubble" style="background:radial-gradient(circle at 30% 24%,rgba(255,255,255,.65),transparent 12%),linear-gradient(145deg,${o.color},${shade(o.color,-8)})"></span><span class="choice-content"><span class="${o.kind==='number'?'choice-number':o.kind==='shape'?'choice-shape':'choice-symbol'}">${o.symbol}</span></span><span class="choice-label">${o.label}</span>`;b.addEventListener('click',()=>selectChoice(b,o));choicesEl.appendChild(b);if(i===0)setTimeout(()=>setTvFocus(b),60)});setTimeout(()=>speak(state.currentQuestion.speech),240)}
function selectChoice(button,o){if(state.locked)return;ensureAudio();if(!o.correct){state.streak=0;button.classList.remove('wrong-shake');void button.offsetWidth;button.classList.add('wrong-shake');softWrongSound();speak('حاول مرة أخرى');setTimeout(()=>button.classList.remove('wrong-shake'),450);return}state.locked=true;state.streak++;button.classList.add('correct-pop');state.stars++;starCount.textContent=state.stars;localStorage.setItem('bubbleSafariBest',String(Math.max(state.stars,Number(localStorage.getItem('bubbleSafariBest')||0))));successSound();showSuccess();setTimeout(()=>{feedback.classList.remove('show');state.round++;if(state.round>=state.totalRounds)finishGame();else{state.locked=false;renderQuestion()}},980)}
function showSuccess(){const base=[['رائع!','وجدتها'],['أحسنت!','إجابة جميلة'],['ممتاز!','استمر يا بطل'],['واو!','أنت رائع']],m=state.streak>=3?['مذهل!','ثلاث إجابات رائعة']:randomFrom(base);feedbackTitle.textContent=m[0];feedbackSubtitle.textContent=m[1];feedbackIcon.textContent=state.streak>=3?'🏅':'★';feedback.classList.add('show');burstConfetti();speak(m[0])}
function burstConfetti(){confetti.innerHTML='';const colors=['#ffd45b','#ff7c68','#75c9e8','#81c96c','#ad92e8','#ff9fc4'];for(let i=0;i<24;i++){const p=document.createElement('i');p.className='confetti-piece';p.style.background=colors[i%colors.length];p.style.setProperty('--x',`${(Math.random()-.5)*620}px`);p.style.setProperty('--y',`${(Math.random()-.72)*470}px`);p.style.setProperty('--r',`${(Math.random()-.5)*720}deg`);confetti.appendChild(p)}setTimeout(()=>confetti.innerHTML='',850)}
function startGame(age){state.age=age;state.round=0;state.stars=0;state.streak=0;state.locked=false;state.lastAnimal=null;state.lastType=null;starCount.textContent='0';showScreen('game');renderQuestion()}
function finishGame(){cancelSpeech();state.locked=false;finalStars.textContent=state.stars;showScreen('finish');successSound(true);setTimeout(()=>speak(`أحسنت! جمعت ${state.stars} نجمة`),280)}
function ensureAudio(){if(state.muted)return null;if(!state.audioContext){const C=window.AudioContext||window.webkitAudioContext;if(!C)return null;state.audioContext=new C()}if(state.audioContext.state==='suspended')state.audioContext.resume();return state.audioContext}
function tone(f,w,d,g=.08,type='sine'){const c=ensureAudio();if(!c||state.muted)return;const o=c.createOscillator(),v=c.createGain();o.type=type;o.frequency.setValueAtTime(f,w);v.gain.setValueAtTime(0,w);v.gain.linearRampToValueAtTime(g,w+.015);v.gain.exponentialRampToValueAtTime(.001,w+d);o.connect(v).connect(c.destination);o.start(w);o.stop(w+d+.03)}
function successSound(big=false){const c=ensureAudio();if(!c)return;const t=c.currentTime;tone(523,t,.17);tone(659,t+.09,.18,.07);tone(784,t+.18,big?.42:.24);if(big)tone(1046,t+.29,.45,.065)}function softWrongSound(){const c=ensureAudio();if(!c)return;const t=c.currentTime;tone(310,t,.12,.035);tone(270,t+.08,.14,.03)}
function cancelSpeech(){if('speechSynthesis'in window)speechSynthesis.cancel()}function speak(text){if(state.muted||!('speechSynthesis'in window))return;cancelSpeech();const u=new SpeechSynthesisUtterance(text);u.lang='ar-SA';u.rate=.8;u.pitch=1.08;u.volume=.95;const vs=speechSynthesis.getVoices(),av=vs.find(v=>/^ar[-_]/i.test(v.lang));if(av)u.voice=av;speechSynthesis.speak(u)}
function updateSoundUi(){soundIcon.textContent=state.muted?'🔇':'🔊';soundButton.setAttribute('aria-label',state.muted?'تشغيل الصوت':'كتم الصوت')}
$('#startButton').addEventListener('click',()=>{ensureAudio();showScreen('age')});$('#ageBackButton').addEventListener('click',()=>showScreen('home'));$$('.age-card').forEach(c=>c.addEventListener('click',()=>startGame(c.dataset.age)));replayButton.addEventListener('click',()=>{ensureAudio();if(state.currentQuestion)speak(state.currentQuestion.speech)});soundButton.addEventListener('click',()=>{state.muted=!state.muted;localStorage.setItem('bubbleSafariMuted',state.muted?'1':'0');if(state.muted)cancelSpeech();else{ensureAudio();if(state.currentQuestion)speak(state.currentQuestion.speech)}updateSoundUi()});$('#playAgainButton').addEventListener('click',()=>startGame(state.age));$('#homeButton').addEventListener('click',()=>showScreen('home'));document.addEventListener('pointerdown',()=>ensureAudio(),{once:true});document.addEventListener('focusin',e=>{if(e.target.matches('[data-focusable]')){$$('.tv-focus').forEach(n=>n.classList.remove('tv-focus'));e.target.classList.add('tv-focus')}});updateSoundUi();showScreen('home');if('serviceWorker'in navigator&&location.protocol!=='file:')addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js').catch(()=>{}));
})();