const $=(selector,root=document)=>root.querySelector(selector);
const STORY_AUDIO_BASE='./audio/stories/arin-fox/';
const STORY_AUDIO_VERSION='v35';

const ARIN_FOX_SEGMENTS=[
  {file:'arin-fox-01-intro.wav',chapter:'صباح جميل',caption:'في قرية صغيرة عاشت طفلة لطيفة اسمها أَرين.',theme:'village',actors:['arin']},
  {file:'arin-fox-02-basket.wav',chapter:'هدية للجدة',caption:'جهزت الأم سلة صغيرة لتأخذها أَرين إلى جدتها.',theme:'home',actors:['arin','mother'],basket:true},
  {file:'arin-fox-03-advice.wav',chapter:'نصيحة الأم',caption:'ذكّرت الأم أَرين أن تبقى على الطريق وألا تتبع شخصًا لا تعرفه.',theme:'home',actors:['arin','mother'],basket:true},
  {file:'arin-fox-04-leave-home.wav',chapter:'بداية الرحلة',caption:'حملت أَرين سلتها ولوّحت لأمها وبدأت رحلتها.',theme:'village',actors:['arin'],basket:true},
  {file:'arin-fox-05-forest-road.wav',chapter:'طريق الغابة',caption:'كان الطريق جميلًا والطيور تغرد بين الأشجار.',theme:'forest',actors:['arin'],basket:true},
  {file:'arin-fox-06-fox-appears.wav',chapter:'ضيف بين الأشجار',caption:'فجأة خرج ثعلب من خلف شجرة كبيرة.',theme:'fox',actors:['arin','fox'],basket:true},
  {file:'arin-fox-07-where-going.wav',chapter:'سؤال الثعلب',caption:'سأل الثعلب أَرين إلى أين تذهب، فتذكرت نصيحة أمها.',theme:'fox',actors:['arin','fox'],basket:true},
  {file:'arin-fox-08-basket-smell.wav',chapter:'رائحة السلة',caption:'لاحظ الثعلب السلة، لكن أَرين لم تخبره أين تسكن جدتها.',theme:'fox',actors:['arin','fox'],basket:true},
  {file:'arin-fox-09-shortcut.wav',chapter:'الطريق الأقصر',caption:'فكر الثعلب في طريق أقصر وركض بين الأشجار.',theme:'forest',actors:['fox']},
  {file:'arin-fox-10-flower.wav',chapter:'زهرة للجدة',caption:'اختارت أَرين زهرة قريبة من الطريق ثم تابعت سيرها.',theme:'garden',actors:['arin'],basket:true},
  {file:'arin-fox-11-grandma-door.wav',chapter:'عند بيت الجدة',caption:'وصل الثعلب أولًا وطرق الباب.',theme:'grandma',actors:['fox','grandma']},
  {file:'arin-fox-12-tail.wav',chapter:'الجدة الذكية',caption:'رأت الجدة طرف ذيل الثعلب وعرفت أنه ليس زائرًا تعرفه.',theme:'grandma',actors:['fox','grandma']},
  {file:'arin-fox-13-waiting-fox.wav',chapter:'الثعلب ينتظر',caption:'أغلقت الجدة الباب جيدًا، فجلس الثعلب قرب البيت.',theme:'grandma',actors:['fox']},
  {file:'arin-fox-14-arin-arrives.wav',chapter:'وصول أَرين',caption:'وصلت أَرين ولاحظت أن المكان هادئ جدًا.',theme:'grandma',actors:['arin','fox'],basket:true},
  {file:'arin-fox-15-arin-refuses.wav',chapter:'قرار شجاع',caption:'شعرت أَرين أن شيئًا غير صحيح ورفضت الاقتراب.',theme:'grandma',actors:['arin','fox'],basket:true},
  {file:'arin-fox-16-grandma-calls.wav',chapter:'صوت الجدة',caption:'سمعت أَرين صوت جدتها من داخل البيت فعرفت أنها بخير.',theme:'grandma',actors:['arin','grandma']},
  {file:'arin-fox-17-ranger-arrives.wav',chapter:'حارس الغابة',caption:'وصل حارس الغابة بعدما سمع الأصوات قرب البيت.',theme:'forest',actors:['arin','fox','ranger']},
  {file:'arin-fox-18-ranger-talks.wav',chapter:'حديث هادئ',caption:'شرح الحارس للثعلب أنه لا يجوز إخافة الناس أو دخول بيوتهم.',theme:'forest',actors:['fox','ranger']},
  {file:'arin-fox-19-fox-admits.wav',chapter:'الثعلب يعترف',caption:'اعترف الثعلب أنه كان فضوليًا وأراد معرفة ما في السلة.',theme:'forest',actors:['fox','ranger']},
  {file:'arin-fox-20-lesson.wav',chapter:'درس مهم',caption:'قال الحارس: عندما تريد شيئًا، اسأل بأدب ولا تتبع الآخرين.',theme:'forest',actors:['fox','ranger']},
  {file:'arin-fox-21-grandma-opens.wav',chapter:'الباب يفتح',caption:'عندما أصبح المكان آمنًا، فتحت الجدة الباب وعانقت أَرين.',theme:'garden',actors:['arin','grandma','ranger'],basket:true},
  {file:'arin-fox-22-gift.wav',chapter:'الهدية',caption:'وضعت أَرين السلة على الطاولة وقدمت لجدتها الزهرة الجميلة.',theme:'garden',actors:['arin','grandma'],basket:true},
  {file:'arin-fox-23-fox-apology.wav',chapter:'اعتذار الثعلب',caption:'اقترب الثعلب من بعيد واعتذر عما فعله.',theme:'garden',actors:['arin','grandma','fox'],autoAdvanceDelayMs:900},
  {file:'arin-fox-24-return.wav',chapter:'طريق العودة',caption:'حان وقت العودة، فرافق الحارس أَرين في جزء من الطريق.',theme:'return',actors:['arin','ranger'],basket:true},
  {file:'arin-fox-25-mother-final.wav',chapter:'في البيت',caption:'عادت أَرين إلى أمها وحكت لها عن المغامرة.',theme:'home',actors:['arin','mother']},
  {file:'arin-fox-26-moral.wav',chapter:'ما تعلمته أَرين',caption:'تعلمت أَرين أن اللطف لا يعني الثقة بكل شخص، وأن طلب المساعدة تصرف شجاع.',theme:'ending',actors:['arin','mother']},
  {file:'arin-fox-27-ending.wav',chapter:'النهاية',caption:'أما الثعلب، ففي المرة التالية لوّح من بعيد وقال: صباح الخير! ثم أكمل طريقه.',theme:'ending',actors:['arin','fox']}
];

const STORIES=[{id:'arin-fox',title:'أرين والثعلب',typeLabel:'استمع وشاهد',durationLabel:'8 دقائق',description:'حكاية مصورة بصوت راوية، تعمل تلقائيًا من البداية إلى النهاية.',segments:ARIN_FOX_SEGMENTS}];
const player={story:null,index:0,finished:false,token:0};
const audio=new Audio();audio.preload='auto';
let nextAudio=null;
let autoAdvanceTimer=null;

function storyActor(id,x,y,scale=1,facing='right',mood='smile',pose='stand'){
  const flip=facing==='left'?-scale:scale;
  const wrap=(inner,extra='')=>`<g class="actor actor-${id} ${extra}" transform="translate(${x} ${y}) scale(${flip} ${scale})">${inner}</g>`;
  if(id==='arin'){
    const mouth=mood==='worried'?'M-8 41 Q0 35 8 41':mood==='surprised'?'M-2 40 Q0 47 2 40':mood==='smile'?'M-10 40 Q0 48 10 40':'M-6 41 Q0 44 6 41';
    const leftArm=pose==='wave'?'M-33 96 Q-60 74 -65 49':'M-33 96 Q-53 112 -49 133';
    const rightArm=pose==='hold'?'M35 98 Q51 110 41 130':'M35 96 Q54 110 50 133';
    return wrap(`<ellipse cx="0" cy="181" rx="47" ry="10" fill="#335744" opacity=".14"/><path d="${leftArm}" fill="none" stroke="#f3c8ab" stroke-width="14" stroke-linecap="round"/><path d="${rightArm}" fill="none" stroke="#f3c8ab" stroke-width="14" stroke-linecap="round"/><path d="M-48 79 Q0 52 48 79 L56 155 L-56 155Z" fill="#d76b80"/><path d="M-20 83 Q0 92 20 83 L16 131 L-16 131Z" fill="#fff4e6"/><circle cx="0" cy="35" r="31" fill="#f3c8ab"/><path d="M-32 23 Q-28 -8 0 -12 Q28 -8 32 23 L32 28 Q18 13 0 13 Q-18 13 -32 28Z" fill="#5c4239"/><path d="M-27 20 Q-16 9 -7 10 Q0 12 7 10 Q16 9 27 20" fill="none" stroke="#f8f1f6" stroke-width="4.5" stroke-linecap="round" opacity=".92"/><g class="actor-eyes"><circle cx="-11" cy="35" r="4.5" fill="#253646"/><circle cx="11" cy="35" r="4.5" fill="#253646"/><circle cx="-9.8" cy="33.7" r="1.2" fill="#fff"/><circle cx="12.2" cy="33.7" r="1.2" fill="#fff"/></g><path d="M-2 40 Q0 43 2 40" fill="none" stroke="#d49a83" stroke-width="2"/><path d="${mouth}" fill="none" stroke="#8a4e5b" stroke-width="2.8" stroke-linecap="round"/><circle cx="-18" cy="45" r="4.4" fill="#ef9aad" opacity=".5"/><circle cx="18" cy="45" r="4.4" fill="#ef9aad" opacity=".5"/><path d="M-19 155 L-19 181" stroke="#f3c8ab" stroke-width="12" stroke-linecap="round"/><path d="M19 155 L19 181" stroke="#f3c8ab" stroke-width="12" stroke-linecap="round"/><path d="M-30 181 h22" stroke="#755046" stroke-width="9" stroke-linecap="round"/><path d="M8 181 h22" stroke="#755046" stroke-width="9" stroke-linecap="round"/>`,pose==='walk'?'actor-walk':'actor-bob');
  }
  if(id==='mother'){
    const rightArm=pose==='point'?'M42 100 Q70 86 86 64':pose==='wave'?'M42 100 Q72 75 76 49':'M42 100 Q60 112 64 135';
    return wrap(`<ellipse cx="0" cy="192" rx="51" ry="10" fill="#335744" opacity=".12"/><path d="M-42 100 Q-59 114 -50 135" fill="none" stroke="#efc4a7" stroke-width="15" stroke-linecap="round"/><path class="${pose==='wave'?'actor-arm-wave':''}" d="${rightArm}" fill="none" stroke="#efc4a7" stroke-width="15" stroke-linecap="round"/><path d="M-54 84 Q0 55 54 84 L62 170 L-62 170Z" fill="#72b39d"/><path d="M-20 90 Q0 99 20 90 L16 160 L-16 160Z" fill="#f2f3ec" opacity=".85"/><circle cx="0" cy="36" r="32" fill="#efc4a7"/><path d="M-34 27 Q-28 -10 0 -13 Q28 -10 34 27 L30 4 Q0 -17 -30 4Z" fill="#4f4038"/><path d="M-17 20 Q0 13 17 20" fill="none" stroke="#f7efe3" stroke-width="4" stroke-linecap="round" opacity=".75"/><g class="actor-eyes"><circle cx="-11" cy="35" r="4" fill="#293b48"/><circle cx="11" cy="35" r="4" fill="#293b48"/><circle cx="-10" cy="34" r="1.1" fill="#fff"/><circle cx="12" cy="34" r="1.1" fill="#fff"/></g><path d="M-8 50 Q0 57 8 50" fill="none" stroke="#895766" stroke-width="2.8" stroke-linecap="round"/><path d="M-20 170 L-20 194" stroke="#efc4a7" stroke-width="12" stroke-linecap="round"/><path d="M20 170 L20 194" stroke="#efc4a7" stroke-width="12" stroke-linecap="round"/><path d="M-31 193 h24" stroke="#547d70" stroke-width="10" stroke-linecap="round"/><path d="M7 193 h24" stroke="#547d70" stroke-width="10" stroke-linecap="round"/>`,'actor-bob');
  }
  if(id==='grandma'){
    if(pose==='window') return `<g class="actor actor-grandma"><circle cx="${x}" cy="${y}" r="28" fill="#e8c3a8"/><path d="M${x-27} ${y-12} Q${x} ${y-43} ${x+27} ${y-12}" fill="none" stroke="#edf0ef" stroke-width="15" stroke-linecap="round"/><circle cx="${x-10}" cy="${y}" r="10" fill="none" stroke="#5b6068" stroke-width="3"/><circle cx="${x+10}" cy="${y}" r="10" fill="none" stroke="#5b6068" stroke-width="3"/><line x1="${x}" y1="${y}" x2="${x}" y2="${y}" stroke="#5b6068" stroke-width="3"/><g class="actor-eyes"><circle cx="${x-10}" cy="${y}" r="3" fill="#283946"/><circle cx="${x+10}" cy="${y}" r="3" fill="#283946"/></g><path d="M${x-7} ${y+14} Q${x} ${y+20} ${x+7} ${y+14}" fill="none" stroke="#845b65" stroke-width="2.5"/></g>`;
    return wrap(`<ellipse cx="0" cy="183" rx="46" ry="10" fill="#335744" opacity=".12"/><path d="M-39 97 Q-54 112 -46 132" fill="none" stroke="#e8c3a8" stroke-width="13" stroke-linecap="round"/><path d="M39 97 Q55 111 58 131" fill="none" stroke="#e8c3a8" stroke-width="13" stroke-linecap="round"/><path d="M-49 86 Q0 58 49 86 L57 161 L-57 161Z" fill="#9e91d9"/><circle cx="0" cy="40" r="30" fill="#e8c3a8"/><path d="M-29 29 Q0 -7 29 29" fill="none" stroke="#edf0ef" stroke-width="16" stroke-linecap="round"/><circle cx="-11" cy="40" r="11" fill="none" stroke="#5b6068" stroke-width="3"/><circle cx="11" cy="40" r="11" fill="none" stroke="#5b6068" stroke-width="3"/><g class="actor-eyes"><circle cx="-11" cy="40" r="3" fill="#283946"/><circle cx="11" cy="40" r="3" fill="#283946"/></g><path d="M-7 54 Q0 60 7 54" fill="none" stroke="#845b65" stroke-width="2.5"/><path d="M-18 161 L-18 184" stroke="#e8c3a8" stroke-width="11" stroke-linecap="round"/><path d="M18 161 L18 184" stroke="#e8c3a8" stroke-width="11" stroke-linecap="round"/><path d="M-26 184 h18" stroke="#6d5c87" stroke-width="8" stroke-linecap="round"/><path d="M8 184 h18" stroke="#6d5c87" stroke-width="8" stroke-linecap="round"/>`,'actor-bob');
  }
  if(id==='fox'){
    if(pose==='run'){
      const runMouth=mood==='thinking'?'M-45 66 Q-33 62 -21 66':'M-47 66 Q-34 73 -22 66';
      return wrap(`<ellipse cx="20" cy="154" rx="70" ry="11" fill="#335744" opacity=".12"/><path class="fox-tail" d="M62 104 Q118 73 154 104 Q153 134 121 148 Q90 157 58 136" fill="#f38a4b" stroke="#a94e2b" stroke-width="2.2"/><path d="M118 119 Q139 111 151 123 Q143 136 125 139 Z" fill="#fff2ce"/><ellipse cx="20" cy="112" rx="58" ry="34" fill="#f38a4b" stroke="#a94e2b" stroke-width="2.2"/><ellipse cx="-22" cy="57" rx="30" ry="28" fill="#f38a4b" stroke="#a94e2b" stroke-width="2.2"/><path d="M-43 33 L-29 3 L-9 34 Z" fill="#f38a4b" stroke="#a94e2b" stroke-width="2.2"/><path d="M-3 33 L10 7 L27 35 Z" fill="#f38a4b" stroke="#a94e2b" stroke-width="2.2"/><path d="M-35 32 L-28 14 L-14 29 Z" fill="#ffe08a"/><path d="M3 32 L10 16 L20 31 Z" fill="#ffe08a"/><g class="actor-eyes"><circle cx="-31" cy="54" r="4.6" fill="#233846"/><circle cx="-15" cy="54" r="4.6" fill="#233846"/></g><path d="M-48 63 Q-42 83 -22 87 Q-2 83 2 63 Q-18 47 -36 52 Z" fill="#fff1df"/><ellipse cx="-44" cy="63" rx="6" ry="5" fill="#2f2b29"/><path d="${runMouth}" fill="none" stroke="#9d6049" stroke-width="2.6" stroke-linecap="round"/><path d="M-2 141 Q16 126 34 138" fill="none" stroke="#d5793d" stroke-width="10" stroke-linecap="round"/><path d="M31 141 Q49 126 67 138" fill="none" stroke="#d5793d" stroke-width="10" stroke-linecap="round"/>`,'actor-walk');
    }
    const eyeLeft = mood==='thinking' ? -11.5 : -14;
    const eyeRight = mood==='thinking' ? 9.5 : 8;
    const mouth = mood==='sorry' ? 'M-9 50 Q0 42 9 50' : mood==='thinking' ? 'M-8 48 Q0 45 8 48' : 'M-12 47 Q0 57 12 47';
    const browL = mood==='sorry' ? 'M-26 18 Q-18 14 -10 18' : mood==='thinking' ? 'M-26 16 Q-18 11 -9 16' : 'M-26 18 Q-18 13 -9 18';
    const browR = mood==='sorry' ? 'M2 16 Q9 13 17 16' : mood==='thinking' ? 'M2 18 Q10 13 19 18' : 'M2 17 Q10 13 19 17';
    const armLeft = pose==='wave' ? 'M-44 107 Q-58 83 -64 61' : 'M-44 107 Q-55 129 -55 153';
    const armRight = pose==='wave' ? 'M44 107 Q57 82 63 62' : 'M44 107 Q55 129 55 153';
    return wrap(`<ellipse cx="0" cy="214" rx="49" ry="10" fill="#335744" opacity=".12"/><path class="fox-tail" d="M33 155 Q103 129 114 176 Q100 203 66 199 Q41 194 24 178" fill="#f47c43" stroke="#ab4d2a" stroke-width="3"/><path d="M76 177 Q98 172 110 183 Q101 197 82 196 Z" fill="#fff4d0"/><path d="${armLeft}" fill="none" stroke="#f47c43" stroke-width="18" stroke-linecap="round"/><path d="${armRight}" fill="none" stroke="#f47c43" stroke-width="18" stroke-linecap="round"/><rect x="-52" y="58" width="104" height="129" rx="38" fill="#f47c43" stroke="#ab4d2a" stroke-width="3"/><ellipse cx="0" cy="124" rx="31" ry="53" fill="#efe0ad" opacity=".98"/><circle cx="0" cy="40" r="43" fill="#f47c43" stroke="#ab4d2a" stroke-width="3"/><path d="M-31 11 L-12 -29 L6 8 Z" fill="#f47c43" stroke="#ab4d2a" stroke-width="3"/><path d="M31 11 L12 -29 L-6 8 Z" fill="#f47c43" stroke="#ab4d2a" stroke-width="3" transform="scale(-1 1)"/><path d="M-23 10 L-11 -16 L-1 8 Z" fill="#ffe07d"/><path d="M23 10 L11 -16 L1 8 Z" fill="#ffe07d" transform="scale(-1 1)"/><path d="${browL}" fill="none" stroke="#c89238" stroke-width="5" stroke-linecap="round"/><path d="${browR}" fill="none" stroke="#c89238" stroke-width="5" stroke-linecap="round"/><g class="actor-eyes"><circle cx="${eyeLeft}" cy="33" r="11.5" fill="#fff"/><circle cx="${eyeRight}" cy="34" r="11.5" fill="#fff"/><circle cx="${eyeLeft+1.5}" cy="34" r="4.2" fill="#1d2d38"/><circle cx="${eyeRight+1.5}" cy="35" r="4.2" fill="#1d2d38"/><circle cx="${eyeLeft+3}" cy="31.7" r="1.2" fill="#fff"/><circle cx="${eyeRight+3}" cy="32.7" r="1.2" fill="#fff"/></g><ellipse cx="10" cy="47" rx="27" ry="22" fill="#f3d66b"/><path d="M-9 61 Q12 73 23 60 Q25 39 6 29 Q-10 35 -17 48 Z" fill="#f4d56b" opacity=".72"/><ellipse cx="18" cy="42" rx="10" ry="8" fill="#54464f" stroke="#2f2930" stroke-width="2"/><ellipse cx="20" cy="39" rx="4" ry="2.6" fill="#fff" opacity=".75"/><path d="M-1 45 h10" stroke="#8a6239" stroke-width="2.2"/><path d="${mouth}" fill="none" stroke="#9a6436" stroke-width="3" stroke-linecap="round"/><path d="M-21 46 l-18 4" stroke="#695258" stroke-width="2.6" stroke-linecap="round"/><path d="M-21 52 l-18 0" stroke="#695258" stroke-width="2.6" stroke-linecap="round"/><path d="M20 47 l17 4" stroke="#695258" stroke-width="2.6" stroke-linecap="round"/><path d="M20 53 l18 1" stroke="#695258" stroke-width="2.6" stroke-linecap="round"/><path d="M-55 153 Q-53 171 -41 177" fill="none" stroke="#4c4651" stroke-width="18" stroke-linecap="round"/><path d="M55 153 Q53 171 41 177" fill="none" stroke="#4c4651" stroke-width="18" stroke-linecap="round"/><path d="M-21 188 L-21 212" stroke="#f47c43" stroke-width="18" stroke-linecap="round"/><path d="M21 188 L21 212" stroke="#f47c43" stroke-width="18" stroke-linecap="round"/><path d="M-33 212 h25" stroke="#4c4651" stroke-width="14" stroke-linecap="round"/><path d="M8 212 h25" stroke="#4c4651" stroke-width="14" stroke-linecap="round"/>`,pose==='walk'?'actor-walk':'actor-bob');
  }
  if(id==='ranger'){
    const arm=pose==='stop'?'M39 103 Q61 84 84 80':'M39 103 Q59 114 62 137';
    return wrap(`<ellipse cx="0" cy="195" rx="49" ry="10" fill="#335744" opacity=".12"/><path d="M-40 103 Q-56 116 -49 137" fill="none" stroke="#c99672" stroke-width="13" stroke-linecap="round"/><path d="${arm}" fill="none" stroke="#c99672" stroke-width="13" stroke-linecap="round"/><path d="M-47 85 Q0 62 47 85 L43 168 H-43 Z" fill="#6f9273"/><path d="M-18 92 H18 V159 H-18 Z" fill="#89a794" opacity=".4"/><circle cx="0" cy="40" r="30" fill="#c99672"/><path d="M-30 18 H30 L22 29 H-22 Z" fill="#577e5d"/><path d="M-31 31 Q0 5 31 31 L25 18 Q0 8 -25 18 Z" fill="#344046"/><path d="M-18 30 Q0 18 18 30" fill="none" stroke="#90ae95" stroke-width="3.5" stroke-linecap="round" opacity=".75"/><g class="actor-eyes"><circle cx="-10" cy="40" r="3.5" fill="#293946"/><circle cx="10" cy="40" r="3.5" fill="#293946"/><circle cx="-9" cy="39" r="1" fill="#fff"/><circle cx="11" cy="39" r="1" fill="#fff"/></g><path d="M-7 54 Q0 60 7 54" fill="none" stroke="#80594e" stroke-width="2.6"/><path d="M-16 168 L-16 194" stroke="#c99672" stroke-width="11" stroke-linecap="round"/><path d="M16 168 L16 194" stroke="#c99672" stroke-width="11" stroke-linecap="round"/><path d="M-25 194 h18" stroke="#4e7657" stroke-width="8" stroke-linecap="round"/><path d="M7 194 h18" stroke="#4e7657" stroke-width="8" stroke-linecap="round"/>`,'actor-bob');
  }
  return '';
}
function storyBasket(x,y,scale=1){return `<g class="story-basket" transform="translate(${x} ${y}) scale(${scale})"><path d="M-25 8 Q0 -9 25 8 L21 36 L-21 36Z" fill="#c79247" stroke="#8b6538" stroke-width="3"/><path d="M-15 8 Q0 -18 15 8" fill="none" stroke="#8b6538" stroke-width="4" stroke-linecap="round"/></g>`}
function storyHouse(x=565,y=190,scale=1){return `<g class="story-house" transform="translate(${x} ${y}) scale(${scale})"><ellipse cx="110" cy="214" rx="122" ry="12" fill="#335744" opacity=".1"/><rect x="0" y="40" width="220" height="170" rx="12" fill="#fff5e0" stroke="#c99d69" stroke-width="5"/><path d="M-28 58 L110 -42 L248 58Z" fill="#d67257"/><rect x="96" y="118" width="56" height="92" rx="8" fill="#9b7552"/><rect x="28" y="84" width="56" height="52" rx="8" fill="#bfe4ef" stroke="#8cb8c7" stroke-width="4"/></g>`}
function storyLayout(segment={}){
  const f=segment.file||'cover',theme=segment.theme||'forest';
  const out={house:['village','home','grandma','garden'].includes(theme),path:['village','forest','fox','return','ending'].includes(theme),actors:[],basket:!!segment.basket,extras:''};
  const add=(id,x,y,s=1,face='right',mood='smile',pose='stand')=>out.actors.push({id,x,y,s,face,mood,pose});
  switch(f){
    case 'arin-fox-01-intro.wav':add('arin',360,238,1.05);break;
    case 'arin-fox-02-basket.wav':add('arin',305,240,1,'right','smile','hold');add('mother',500,222,1.06,'left');break;
    case 'arin-fox-03-advice.wav':add('arin',305,240,1,'right','smile','hold');add('mother',500,222,1.06,'left','smile','point');break;
    case 'arin-fox-04-leave-home.wav':add('arin',330,240,1,'right','smile','walk');add('mother',650,222,.94,'left','smile','wave');break;
    case 'arin-fox-05-forest-road.wav':add('arin',370,240,1.02,'right','smile','walk');break;
    case 'arin-fox-06-fox-appears.wav':add('arin',270,242,1,'right','surprised','hold');add('fox',602,246,.92,'left');break;
    case 'arin-fox-07-where-going.wav':add('arin',275,242,1,'right','smile','hold');add('fox',602,246,.92,'left');break;
    case 'arin-fox-08-basket-smell.wav':add('arin',270,242,1,'right','worried','hold');add('fox',602,246,.92,'left','thinking');break;
    case 'arin-fox-09-shortcut.wav':add('fox',470,288,1.05,'right','thinking','run');break;
    case 'arin-fox-10-flower.wav':add('arin',360,242,1,'right','smile','hold');out.extras='<g><path d="M305 430V395" stroke="#5ca867" stroke-width="4"/><circle cx="305" cy="389" r="9" fill="#ff8f8f"/><circle cx="296" cy="394" r="8" fill="#ffd75b"/><circle cx="314" cy="394" r="8" fill="#a98be6"/></g>';break;
    case 'arin-fox-11-grandma-door.wav':add('grandma',615,286,1,'left','smile','window');add('fox',450,304,.94,'right');break;
    case 'arin-fox-12-tail.wav':add('grandma',615,286,1,'left','smile','window');add('fox',450,304,.94,'right','thinking');break;
    case 'arin-fox-13-waiting-fox.wav':add('fox',500,250,.9,'right','thinking');break;
    case 'arin-fox-14-arin-arrives.wav':add('arin',238,244,1,'right','surprised','hold');add('fox',520,250,.88,'left');break;
    case 'arin-fox-15-arin-refuses.wav':add('arin',228,245,1,'right','worried','hold');add('fox',525,250,.88,'left','sorry');break;
    case 'arin-fox-16-grandma-calls.wav':add('arin',260,244,1,'right','smile','hold');add('grandma',615,286,1,'left','smile','window');break;
    case 'arin-fox-17-ranger-arrives.wav':add('arin',205,245,.95,'right','worried','hold');add('ranger',430,222,1,'right','smile','stop');add('fox',620,250,.82,'left','thinking');break;
    case 'arin-fox-18-ranger-talks.wav':add('ranger',385,222,1.02,'right','smile','stop');add('fox',610,250,.82,'left','thinking');break;
    case 'arin-fox-19-fox-admits.wav':add('ranger',385,222,1.02,'right');add('fox',610,250,.82,'left','sorry');break;
    case 'arin-fox-20-lesson.wav':add('ranger',385,222,1.02,'right','smile','stop');add('fox',610,250,.82,'left','sorry');break;
    case 'arin-fox-21-grandma-opens.wav':add('arin',390,245,1,'right','smile');add('grandma',550,228,1,'left');add('ranger',710,226,.82,'left');break;
    case 'arin-fox-22-gift.wav':add('arin',420,245,1,'right','smile','hold');add('grandma',560,228,1,'left');break;
    case 'arin-fox-23-fox-apology.wav':add('fox',280,252,.84,'right','sorry');add('arin',448,245,1,'left');add('grandma',600,228,.98,'left');break;
    case 'arin-fox-24-return.wav':add('ranger',260,223,.92,'right','smile','wave');add('arin',470,245,1,'right','smile','walk');out.path=true;out.house=false;break;
    case 'arin-fox-25-mother-final.wav':add('arin',350,242,1,'right','smile','hold');add('mother',525,222,1.05,'left');break;
    case 'arin-fox-26-moral.wav':add('arin',355,242,1,'right','smile');add('mother',525,222,1.05,'left');break;
    case 'arin-fox-27-ending.wav':add('arin',280,245,.96,'right','smile');add('fox',618,250,.84,'left','smile');out.house=false;break;
    default:add('arin',300,242,1,'right','smile','hold');add('fox',590,305,.96,'left');out.house=false;out.path=true;
  }
  return out;
}
function sceneSvg(segment={}){
  const theme=segment.theme||'forest',night=theme==='grandma',layout=storyLayout(segment);
  const actors=layout.actors.map(a=>storyActor(a.id,a.x,a.y,a.s,a.face,a.mood,a.pose)).join('');
  const basket=layout.basket?storyBasket(layout.actors.find(a=>a.id==='arin')?.x+44||405,375,.82):'';
  return `<svg class="story-svg" viewBox="0 0 900 520" aria-hidden="true"><defs><linearGradient id="storySky" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${night?'#a7d1e3':'#bfeaf4'}"/><stop offset="1" stop-color="${night?'#edf4df':'#f4f7d2'}"/></linearGradient><linearGradient id="storyGround" x1="0" y1="0" x2="1" y2="0"><stop offset="0" stop-color="#a9d97d"/><stop offset="1" stop-color="#74ba67"/></linearGradient></defs><rect width="900" height="520" fill="url(#storySky)"/><circle cx="106" cy="90" r="46" fill="#ffd963" opacity="${night?'.55':'1'}"/><g class="story-cloud-svg" fill="#fff" opacity=".88"><ellipse cx="320" cy="90" rx="60" ry="25"/><ellipse cx="360" cy="84" rx="40" ry="30"/><ellipse cx="399" cy="94" rx="52" ry="23"/></g><path d="M0 330 C130 255 250 290 360 324 C500 258 650 264 900 320 L900 520 L0 520Z" fill="#95ce78"/><path d="M0 382 C170 330 320 348 470 380 C630 330 760 344 900 376 L900 520 L0 520Z" fill="url(#storyGround)"/>${layout.path?'<path d="M362 520 C382 453 420 413 468 384 C516 356 548 330 564 298" fill="none" stroke="#efdaa7" stroke-width="76" stroke-linecap="round" opacity=".92"/>':''}<g class="story-tree-svg"><rect x="88" y="220" width="36" height="176" rx="16" fill="#8a613c"/><circle cx="106" cy="198" r="74" fill="#5fa95a"/><circle cx="63" cy="216" r="50" fill="#6fba63"/><circle cx="148" cy="214" r="52" fill="#6fba63"/></g><g class="story-tree-svg"><rect x="738" y="224" width="34" height="172" rx="16" fill="#8a613c"/><circle cx="756" cy="204" r="70" fill="#5b9f55"/><circle cx="716" cy="220" r="45" fill="#70b866"/><circle cx="796" cy="217" r="47" fill="#70b866"/></g>${layout.house?storyHouse():''}${layout.extras}${actors}${basket}<g class="story-sparkles-svg" fill="#fff6a5"><circle cx="250" cy="164" r="5"/><circle cx="670" cy="130" r="4"/><circle cx="440" cy="225" r="3"/></g></svg>`;
}

function installScreens(){
  $('#storyScreen')?.remove();
  const stage=$('.stage');if(!stage)return;
  const library=document.createElement('section');library.id='storyLibraryScreen';library.className='screen story-library-screen';library.setAttribute('aria-hidden','true');library.innerHTML=`<div class="story-library-shell"><div class="story-library-topbar"><button class="back-button focusable story-library-back" id="storyLibraryBackButton" type="button" data-focusable aria-label="العودة للرئيسية">←</button><div class="story-library-heading"><span class="eyebrow">استمع وشاهد</span><h2>مكتبة القصص</h2><p>اختر الغلاف، وستبدأ الحكاية بصوت الراوية.</p></div></div><div class="story-library-grid" id="storyLibraryGrid"></div></div>`;
  const playerScreen=document.createElement('section');playerScreen.id='storyNarratedScreen';playerScreen.className='screen story-screen';playerScreen.setAttribute('aria-hidden','true');playerScreen.innerHTML=`<div class="story-player-shell"><div class="story-player-topbar"><button class="back-button focusable story-back" id="storyBackButton" type="button" data-focusable aria-label="العودة لمكتبة القصص">←</button><div class="story-player-heading"><span class="eyebrow">قصة مسموعة مصورة</span><h2 id="storyTitle">أرين والثعلب</h2><p id="storyChapterTitle">بداية الحكاية</p></div><div class="story-progress" id="storyProgress" role="progressbar" aria-valuemin="1" aria-valuemax="27" aria-valuenow="1"><strong id="storyProgressText">1 / 27</strong><span class="story-progress-track"><span id="storyProgressFill"></span></span></div></div><div class="story-stage-card"><div class="story-visual" id="storyVisual"></div><div class="story-caption-panel"><span class="story-kicker">الراوية</span><p id="storyNarration">كان يا ما كان...</p><span class="story-path-note" id="storyPathNote">تعمل القصة تلقائيًا من البداية إلى النهاية.</span></div></div><div class="story-controls" id="storyControls"><button class="story-control focusable" id="storyPlayPauseButton" type="button" data-focusable data-autofocus><span class="story-control-icon" id="storyPlayPauseIcon">Ⅱ</span><span id="storyPlayPauseText">إيقاف مؤقت</span></button><button class="story-control focusable" id="storyReplaySegmentButton" type="button" data-focusable><span class="story-control-icon">↻</span><span>إعادة الجزء</span></button></div><div class="story-ending hidden" id="storyEnding" aria-hidden="true"><strong>انتهت الحكاية ✨</strong><span>هل نسمعها مرة أخرى؟</span><div class="story-ending-actions"><button class="story-control focusable" id="storyReplayStoryButton" type="button" data-focusable><span class="story-control-icon">↻</span><span>مرة أخرى</span></button><button class="story-control focusable" id="storyChooseAnotherButton" type="button" data-focusable><span class="story-control-icon">▦</span><span>مكتبة القصص</span></button></div></div></div>`;
  stage.insertBefore(library,$('#gameScreen'));stage.insertBefore(playerScreen,$('#gameScreen'));
}

function renderLibrary(){
  const grid=$('#storyLibraryGrid');if(!grid)return;grid.innerHTML='';
  STORIES.forEach((story,index)=>{const card=document.createElement('button');card.type='button';card.className='story-cover-card focusable';card.dataset.focusable='';if(index===0)card.dataset.autofocus='';card.innerHTML=`<span class="story-cover-art">${sceneSvg({theme:'forest',actors:['arin','fox'],basket:true})}<span class="story-cover-play">▶</span></span><span class="story-cover-copy"><span class="story-type-badge">${story.typeLabel}</span><strong>${story.title}</strong><small>${story.description}</small><span class="story-duration">◷ ${story.durationLabel}</span></span>`;card.addEventListener('click',()=>openStory(story.id));grid.appendChild(card)});
}

function setFocus(el){if(!el)return;document.querySelectorAll('.tv-focus').forEach(node=>node.classList.remove('tv-focus'));try{el.focus({preventScroll:true})}catch{el.focus()}el.classList.add('tv-focus')}
function setActiveScreen(id){document.querySelectorAll('.screen').forEach(screen=>{const active=screen.id===id;screen.classList.toggle('screen-active',active);screen.setAttribute('aria-hidden',active?'false':'true')});$('#hud')?.classList.add('hidden');$('#settingsButton')?.classList.add('hidden');$('#soundButton')?.classList.add('hidden');setTimeout(()=>setFocus($(`#${id} [data-autofocus]`)||$(`#${id} [data-focusable]`)),60)}
function returnHome(){stopAudio();document.querySelectorAll('.screen').forEach(screen=>{const active=screen.id==='homeScreen';screen.classList.toggle('screen-active',active);screen.setAttribute('aria-hidden',active?'false':'true')});$('#settingsButton')?.classList.remove('hidden');$('#soundButton')?.classList.remove('hidden');setTimeout(()=>setFocus($('#startButton')),60)}
function openLibrary(){stopAudio();renderLibrary();setActiveScreen('storyLibraryScreen')}
function audioPath(segment){return `${STORY_AUDIO_BASE}${segment.file}?v=${STORY_AUDIO_VERSION}`}
function clearAutoAdvanceTimer(){if(autoAdvanceTimer){clearTimeout(autoAdvanceTimer);autoAdvanceTimer=null}}
function stopAudio(){clearAutoAdvanceTimer();player.token++;audio.pause();audio.removeAttribute('src');audio.load();nextAudio=null;player.finished=false}
function preloadNext(){const next=player.story?.segments?.[player.index+1];if(!next){nextAudio=null;return}nextAudio=new Audio();nextAudio.preload='auto';nextAudio.src=audioPath(next)}
function syncControls(){const paused=audio.paused||player.finished;const text=$('#storyPlayPauseText'),icon=$('#storyPlayPauseIcon'),button=$('#storyPlayPauseButton');if(!button)return;button.disabled=player.finished;if(text)text.textContent=paused?'متابعة':'إيقاف مؤقت';if(icon)icon.textContent=paused?'▶':'Ⅱ'}
function renderSegment(){const story=player.story,segment=story?.segments?.[player.index];if(!story||!segment)return;$('#storyChapterTitle').textContent=segment.chapter;$('#storyNarration').textContent=segment.caption;const visual=$('#storyVisual');visual.className=`story-visual story-theme-${segment.theme}`;visual.innerHTML=`<div class="story-scene-enter">${sceneSvg(segment)}</div>`;const current=player.index+1,total=story.segments.length;$('#storyProgressText').textContent=`${current} / ${total}`;$('#storyProgressFill').style.transform=`scaleX(${current/total})`;$('#storyProgress').setAttribute('aria-valuenow',String(current));$('#storyEnding').classList.add('hidden');$('#storyEnding').setAttribute('aria-hidden','true');$('#storyControls').classList.remove('hidden');player.finished=false;syncControls()}
async function playSegment(restart=true){const segment=player.story?.segments?.[player.index];if(!segment)return;clearAutoAdvanceTimer();const token=++player.token;renderSegment();if(restart||audio.src!==new URL(audioPath(segment),location.href).href){audio.src=audioPath(segment);audio.load()}audio.muted=localStorage.getItem('bubbleSafariMuted')==='1';preloadNext();try{await audio.play();if(token===player.token)syncControls()}catch{if(token===player.token){syncControls();$('#storyPathNote').textContent='اضغط متابعة لبدء صوت الراوية.'}}}
function openStory(id){const story=STORIES.find(item=>item.id===id)||STORIES[0];stopAudio();player.story=story;player.index=0;player.finished=false;$('#storyTitle').textContent=story.title;$('#storyPathNote').textContent='تعمل القصة تلقائيًا من البداية إلى النهاية.';setActiveScreen('storyNarratedScreen');playSegment(true)}
function finishStory(){clearAutoAdvanceTimer();player.finished=true;audio.pause();syncControls();$('#storyControls').classList.add('hidden');$('#storyEnding').classList.remove('hidden');$('#storyEnding').setAttribute('aria-hidden','false');$('#storyPathNote').textContent='انتهت القصة. لن تبدأ قصة أخرى تلقائيًا.';setTimeout(()=>setFocus($('#storyReplayStoryButton')),70)}
function togglePlayback(){if(player.finished)return;if(audio.paused){audio.play().then(syncControls).catch(()=>{syncControls();$('#storyPathNote').textContent='اضغط متابعة لبدء صوت الراوية.'})}else{audio.pause();syncControls()}}
function replaySegment(){if(!player.story)return;audio.currentTime=0;audio.play().then(syncControls).catch(()=>{syncControls();$('#storyPathNote').textContent='اضغط متابعة لبدء صوت الراوية.'})}
function replayStory(){player.index=0;player.finished=false;$('#storyControls').classList.remove('hidden');playSegment(true);setTimeout(()=>setFocus($('#storyPlayPauseButton')),70)}

function wire(){
  const homeCard=$('[data-home-section="stories"]');if(homeCard){homeCard.id='storiesButton';const badge=$('.mode-badge',homeCard),title=$('.mode-copy strong',homeCard),copy=$('.mode-copy small',homeCard);if(badge)badge.textContent='جديد';if(title)title.textContent='القصص';if(copy)copy.textContent='قصص مسموعة ومصورة للأطفال'}
  window.addEventListener('click',event=>{const card=event.target.closest?.('[data-home-section="stories"]');if(card){event.preventDefault();event.stopImmediatePropagation();openLibrary()}},true);
  $('#storyLibraryBackButton').addEventListener('click',returnHome);$('#storyBackButton').addEventListener('click',()=>{stopAudio();setActiveScreen('storyLibraryScreen')});$('#storyPlayPauseButton').addEventListener('click',togglePlayback);$('#storyReplaySegmentButton').addEventListener('click',replaySegment);$('#storyReplayStoryButton').addEventListener('click',replayStory);$('#storyChooseAnotherButton').addEventListener('click',()=>{stopAudio();setActiveScreen('storyLibraryScreen')});
  window.addEventListener('keydown',event=>{if(!$('#storyLibraryScreen')?.classList.contains('screen-active')&&!$('#storyNarratedScreen')?.classList.contains('screen-active'))return;const back=['Escape','BrowserBack','GoBack'].includes(event.key)||[4,27,461,10009].includes(event.keyCode||event.which);if(!back)return;event.preventDefault();event.stopImmediatePropagation();if($('#storyNarratedScreen').classList.contains('screen-active')){stopAudio();setActiveScreen('storyLibraryScreen')}else returnHome()},true);
  audio.addEventListener('ended',()=>{if(player.finished||!player.story)return;const segment=player.story.segments[player.index];const delay=segment?.autoAdvanceDelayMs??350;clearAutoAdvanceTimer();autoAdvanceTimer=setTimeout(()=>{if(player.finished||!player.story)return;if(player.index>=player.story.segments.length-1){finishStory();return}player.index++;playSegment(true)},delay)});audio.addEventListener('play',syncControls);audio.addEventListener('pause',syncControls);audio.addEventListener('error',()=>{clearAutoAdvanceTimer();$('#storyPathNote').textContent='تعذر تشغيل هذا الجزء الآن. اختر إعادة الجزء للمحاولة.';syncControls()});
}

function init(){installScreens();renderLibrary();wire()}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,0),{once:true});else setTimeout(init,0);
